# Generated by Django 6.0.1 on 2026-01-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_contactmessage_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='MOU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('highlights', models.JSONField()),
                ('icon', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('pdf', models.FileField(upload_to='mous/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
