# Generated by Django 6.0.1 on 2026-01-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mou'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mou',
            name='category',
            field=models.CharField(choices=[('cloud', 'Cloud'), ('education', 'Education'), ('security', 'Security'), ('innovation', 'Innovation')], max_length=50),
        ),
        migrations.AlterField(
            model_name='mou',
            name='highlights',
            field=models.JSONField(help_text="Example: ['Point 1', 'Point 2']"),
        ),
        migrations.AlterField(
            model_name='mou',
            name='icon',
            field=models.CharField(help_text='Bootstrap icon class', max_length=50),
        ),
    ]
