# Generated by Django 6.0.1 on 2026-01-14 13:44

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_mou_category_alter_mou_highlights_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Events', 'Events'), ('Activities', 'Activities'), ('Achievements', 'Achievements'), ('Office', 'Office')], max_length=20)),
                ('image', models.ImageField(upload_to=api.models.gallery_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
