# Generated by Django 6.0.1 on 2026-01-14 14:05

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_galleryimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mou',
            name='pdf',
            field=models.FileField(upload_to=api.models.mou_upload_path),
        ),
    ]
