# Generated by Django 6.0.1 on 2026-01-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('workshop', 'Workshop'), ('gallery', 'Gallery')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(blank=True, choices=[('completed', 'Completed'), ('upcoming', 'Upcoming')], max_length=20)),
                ('participants', models.PositiveIntegerField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
