# Generated by Django 6.0.1 on 2026-01-15 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_communityitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityitem',
            name='section',
            field=models.CharField(choices=[('giveback', 'Give Back'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='communityitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='give-gallery/'),
        ),
        migrations.AlterField(
            model_name='communityitem',
            name='item_type',
            field=models.CharField(choices=[('gallery', 'Gallery'), ('workshop', 'Workshop')], max_length=20),
        ),
    ]
