# Generated by Django 5.2.7 on 2026-01-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_careerapplication_id_alter_communityitem_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CpuInquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cpu_model', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('ram', models.CharField(max_length=50)),
                ('storage', models.CharField(max_length=50)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
