# Generated by Django 6.0.1 on 2026-01-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_careerapplication_id_alter_communityitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpuinquiry',
            name='phone',
            field=models.CharField(default=1122, max_length=10),
            preserve_default=False,
        ),
    ]
